# Generated by Django 3.1.1 on 2020-09-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200811_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_en_us',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_hu',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ro',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='longDescription_en_us',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='longDescription_hu',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='longDescription_ro',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en_us',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_hu',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ro',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
