# Generated by Django 3.1.1 on 2020-09-08 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
